sudo: false
language: node_js
node_js:
  - '0.10'
cache:
  directories:
    - node_modules
    - bower_components
before_install:
  - 'export CHROME_BIN=chromium-browser'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'phantomjs --version'
  - 'firefox --version'
before_script:
  - 'npm install -g grunt-cli'
  - 'npm install -g karma-cli'
  - 'npm install -g bower'
  - 'bower install'
after_success:
  - coveralls
